spring:
  application:
    name: gateway

server:
  port: 9092
  servlet:
    context-path: gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka/
    fetch-registry: true #only gateway should fetch registry the other microservices no.
    register-with-eureka: true

zuul:
  sensitive-headers: Cookie
